name: Deploy Next App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout latest code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Build Next.js app
        run: npm run build

      - name: Start or Restart PM2
        shell: bash
        run: |
          if pm2 describe NextDemo > /dev/null; then
            pm2 restart NextDemo
          else
            pm2 start npm --name "NextDemo" -- start
          fi

      - name: Save PM2 process list
        run: pm2 save